MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
